services:
  nginx:
    image: becongmbh/nginx:latest
    hostname: nginx
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - datagerry
    environment:
      NGINX_LOCATION_DEFAULT: "/;/;http://datagerry:4000"
    restart: unless-stopped

  datagerry:
    image: becongmbh/datagerry:latest
    hostname: datagerry
    depends_on:
    - db
    ports:
    - 4000:4000
    environment:
      DATAGERRY_Database_host: "db"
    restart: unless-stopped

  db:
    image: mongo:4.4.18
    hostname: db
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb

volumes:
  mongodb-data:
  mongodb-config:
